# Contains Time Zone Data
zones = {
    'Pacific': -7,
    'Eastern': -4,
    'French': 2,
    'English': 2,
    'German': 2,
    'Russian': 2,
    'Spanish': 2,
    'Taiwan': 8,
    'Korea': 9,
    'Australian Eastern Time': 10
}

#US, EU, KR, TW, CN.

servers = {
    'anathema': 'US',
    'arcanite reaper': 'US',
    'arugal': 'US',
    'ashkandi': 'US',
    'atiesh': 'US',
    'azuresong': 'US',
    'benediction': 'US',
    'bigglesworth': 'US',
    'blaumeux': 'US',
    'bloodsail buccaneers': 'US',
    'deviate delight': 'US',
    'earthfury': 'US',
    'faerlina': 'US',
    'fairbanks': 'US',
    'felstriker': 'US',
    'grobbulus': 'US',
    'heartseeker': 'US',
    'herod': 'US',
    'incendius': 'US',
    'kirtonos': 'US',
    'kromcrush': 'US',
    'kurinnaxx': 'US',
    'loatheb': 'US',
    'mankrik': 'US',
    'myzrael': 'US',
    'netherwind': 'US',
    'old blanchy': 'US',
    'pagle': 'US',
    'rattlegore': 'US',
    'remulos': 'US',
    'skeram': 'US',
    'smolderweb': 'US',
    'stalagg': 'US',
    "sul'thraze": 'US',
    'sulthraze': 'US',
    'sulfuras': 'US',
    'thalnos': 'US',
    'thunderfury': 'US',
    'westfall': 'US',
    'whitemane': 'US',
    'windseeker': 'US',
    'yojamba': 'US',
    'amnennar': 'EU',
    'ashbringer': 'EU',
    'auberdine': 'EU',
    'bloodfang': 'EU',
    'celebras': 'EU',
    'chromie': 'EU',
    "dragon's call": 'EU',
    "dragons call": 'EU',
    'dragonfang': 'EU',
    'dreadmist': 'EU',
    'earthshaker': 'EU',
    'everlook': 'EU',
    'finkle': 'EU',
    'firemaw': 'EU',
    'flamegor': 'EU',
    'flamelash': 'EU',
    'gandling': 'EU',
    'gehennas': 'EU',
    'golemagg': 'EU',
    'harbinger of doom': 'EU',
    'heartstriker': 'EU',
    'hydraxian waterlords': 'EU',
    'judgement': 'EU',
    'lakeshire': 'EU',
    'lucifron': 'EU',
    'mandokir': 'EU',
    'mirage raceway': 'EU',
    'mograine': 'EU',
    'nethergarde Keep': 'EU',
    'noggenfogger': 'EU',
    'patchwerk': 'EU',
    'pyrewood village': 'EU',
    'razorfen': 'EU',
    'razorgore': 'EU',
    "rhok'delar": 'EU',
    "rhokdelar": 'EU',
    'shazzrah': 'EU',
    'skullflame': 'EU',
    'stonespine': 'EU',
    'sulfuron': 'EU',
    'ten storms': 'EU',
    'transcendence': 'EU',
    'venoxis': 'EU',
    'wyrmthalak': 'EU',
    'zandalar tribe': 'EU',
    'hillsbrad': 'KR',
    'iceblood': 'KR',
    'lokholar': 'KR',
    'ragnaros': 'KR',
    'shimmering flats': 'KR',
    'ivus': 'TW',
    'maraudon': 'TW',
    '乌洛克': 'CN',
    '伊森迪奥斯': 'CN',
    '伦鲁迪洛尔': 'CN',
    '光芒': 'CN',
    '克罗米': 'CN',
    '加丁': 'CN',
    '匕首岭': 'CN',
    '卓越': 'CN',
    '厄运之槌': 'CN',
    '吉兹洛克': 'CN',
    '哈霍兰': 'CN',
    '圣光之愿': 'CN',
    '埃提耶什': 'CN',
    '塞卡尔': 'CN',
    '塞雷布拉斯': 'CN',
    '奎尔塞拉': 'CN',
    '奥罗': 'CN',
    '奥金斧': 'CN',
    '娅尔罗': 'CN',
    '安娜丝塔丽': 'CN',
    '审判': 'CN',
    '寒冰之王': 'CN',
    '寒脊山小径': 'CN',
    '巨人追猎者': 'CN',
    '巨龙沼泽': 'CN',
    '巨龙追猎者': 'CN',
    '巴罗夫': 'CN',
    '布劳缪克丝': 'CN',
    '布鲁': 'CN',
    '希尔盖': 'CN',
    '帕奇维克': 'CN',
    '席瓦莱恩': 'CN',
    '弗莱拉斯': 'CN',
    '德姆塞卡尔': 'CN',
    '怀特迈恩': 'CN',
    '怒炉': 'CN',
    '拉姆斯登': 'CN',
    '无尽风暴': 'CN',
    '无畏': 'CN',
    '曼多基尔': 'CN',
    '木喉要塞': 'CN',
    '末日之刃': 'CN',
    '毁灭之刃': 'CN',
    '比斯巨兽': 'CN',
    '比格沃斯': 'CN',
    '水晶之牙': 'CN',
    '沙尔图拉': 'CN',
    '沙顶': 'CN',
    '法尔班克斯': 'CN',
    '法拉克斯': 'CN',
    '法琳娜': 'CN',
    '流沙岗哨': 'CN',
    '湖畔镇': 'CN',
    '火锤': 'CN',
    '灰烬使者': 'CN',
    '灵风': 'CN',
    '狂野之刃': 'CN',
    '狮心': 'CN',
    '甲虫之墙': 'CN',
    '碧玉矿洞': 'CN',
    '碧空之歌': 'CN',
    '祈福': 'CN',
    '祖尔格拉布': 'CN',
    '神谕林地': 'CN',
    '秩序之源': 'CN',
    '维克尼拉斯': 'CN',
    '维克托': 'CN',
    '维克洛尔': 'CN',
    '维希度斯': 'CN',
    '艾隆纳亚': 'CN',
    '范克瑞斯': 'CN',
    '范沃森': 'CN',
    '莫格莱尼': 'CN',
    '萨弗拉斯': 'CN',
    '萨弗隆': 'CN',
    '觅心者': 'CN',
    '诺克赛恩': 'CN',
    '诺格弗格': 'CN',
    '赫洛德': 'CN',
    '辛洛斯': 'CN',
    '辛迪加': 'CN',
    '迈克斯纳': 'CN',
    '阿什坎迪': 'CN',
    '阿拉希盆地': 'CN',
    '阿鲁高': 'CN',
    '雷德': 'CN',
    '雷霆之击': 'CN',
    '震地者': 'CN',
    '霜语': 'CN',
    '骨火': 'CN',
    '黑曜石之锋': 'CN',
    '黑石山': 'CN',
    '龙之召唤': 'CN',
    '龙牙': 'CN'
}